dependencies:
  #<org>/<repo>:<version>
  - smartcontractkit/chainlink-brownie-contracts@0.2.0
compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@0.2.0"

dotenv: .env
networks:
  rinkeby:
    eth_price_feed: "0x8A753747A1Fa494EC906cE90E9f37563A8AF630e"

wallets:
  from_key: ${PRIVATE_KEY}
